/*
 * File: app/store/Contacts.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Packt.store.Contacts', {
    extend: 'Ext.data.Store',

    requires: [
        'Packt.proxy.ContactsProxy',
        'Packt.model.Contact'
    ],

    config: {
        model: 'Packt.model.Contact',
        storeId: 'Contacts',
        grouper: {
            groupFn: function(item) {
                if (item.get('givenName')){
                    return item.get('givenName')[0];
                } else if (item.get('familyName')){
                    return item.get('familyName')[0];
                } 
                return "-";

            }
        }
    }
});