/*
 * File: app/model/Contact.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Packt.model.Contact', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'id'
            },
            {
                convert: function(v, rec) {
                    return rec.get('givenName') + ' ' + rec.get('familyName');
                },
                name: 'displayName'
            },
            {
                name: 'phoneNumber'
            },
            {
                name: 'familyName'
            },
            {
                name: 'givenName'
            }
        ]
    }
});